# Sudo-enabled Ubuntu Trusty VM
dist: trusty
sudo: required


# Build, test and deploy to Google Cloud and Heroku
matrix:
  include:
    - language: java
      jdk: oraclejdk8
      # Environment Variables
      env:
        global:
          - GH_REF: github.com/Thebest1209/susi_server.git
    #  before_cache:
    #    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    #    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      # Store Gradle dependency cache and Gradle Wrapper files for next execution
      cache:
        directories:
           - $HOME/.gradle/caches/
           - $HOME/.gradle/wrapper/
      # main build processes
      script:
        - gradle assemble
        - gradle clean
      install: true
      after_success: 
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep_history: true
        on:
          branch: master
    
    
